### ISSUE TITLE
Error when running with recent versions.

### ISSUE THREAD

**Issue by Daniel-Dos** [fnproject/fdk-java#119]
Hello people,

making a simple Hello-World as shown in the README, running the "fn run" command gives me the following exception:

```
Exception in thread "main" java.lang.NoSuchMethodError: com.fnproject.fn.api.InputCoercion.tryCoerceParam(Lcom/fnproject/fn/api/InvocationContext;ILcom/fnproject/fn/api/InputEvent;)Ljava/util/Optional;
	at com.fnproject.fn.runtime.MethodFunctionInvoker.lambda$doInputCoercions$0(MethodFunctionInvoker.java:64)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1471)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:476)
	at com.fnproject.fn.runtime.MethodFunctionInvoker.doInputCoercions(MethodFunctionInvoker.java:66)
	at com.fnproject.fn.runtime.MethodFunctionInvoker.tryInvoke(MethodFunctionInvoker.java:34)
	at com.fnproject.fn.runtime.EntryPoint.run(EntryPoint.java:87)
	at com.fnproject.fn.runtime.EntryPoint.main(EntryPoint.java:27)
ERROR: exit status 1
```

this error appears when I am using within pom.xml at <fdk.version> 1.0.54 </ fdk.version> at 1.0.52.

  When I use version 1.0.51 it works normally ,

**Comment by zootalures** [comment]
Hey - thanks for raising this, we've made some (backwards incompatible) changes to the FDK runtime which is bundled into the base image. 

You can pin functions to a specific runtime and build container in your func.yaml as follows: 

for Java 9 
```
build_image: fnproject/fn-java-fdk-build:jdk9-1.0.54
run_image: fnproject/fn-java-fdk:jdk9-1.0.54
```
or 8: 
```
build_image: fnproject/fn-java-fdk-build:1.0.54
run_image: fnproject/fn-java-fdk:1.0.54
```

Recent versions of the  CLI will auto-pin these with fn init.

**Comment by Daniel-Dos** [comment]
Hi @zootalures ,

thank you, it worked perfectly.
It would be interesting to update the README warning about this, if need be.

Thank you again.
